<?php

namespace AppBundle\Repository;

/**
 * CakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CakeRepository extends \Doctrine\ORM\EntityRepository
{
}
