<?php

namespace AppBundle\Repository;

/**
 * FoobarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoobarRepository extends \Doctrine\ORM\EntityRepository
{
}
